use_frameworks!

target 'TestFramework_Example' do
  pod 'TestFramework', :path => '../'

  target 'TestFramework_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
